# Site settings
title: Low throughput science
email: alex.rubinsteyn@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Machine learning, genomics, immunology.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://rubinsteyn.com" # the base hostname & protocol for your site
twitter_username: iskander
github_username:  iskandr
theme: minima

# Build settings
markdown: kramdown
